name: Snake Game & Quote Update

on:
  schedule:
    - cron: "0 0 * * *"  # every midnight UTC
  workflow_dispatch:

jobs:
  update-snake:
    name: Generate Snake
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: lakshayknows
          outputs: |
            dist/github-contribution-grid-snake-dark.svg

      - name: Push Snake to Profile
        uses: crazy-max/ghaction-github-pages@v4
        with:
          color_snake: '#0A66C2'  # (LinkedIn blue)
          color_dots: '#212121,#212121,#212121,#0A66C2,#0A66C2'  # black & blue mix
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
